name: Installation problem
description: "If you've encountered a reproducible issue with a homebrew-hep package."
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Verification
      description: Please verify that you've followed these steps.
      options:
        - label: I ran `brew update` and am still able to reproduce my issue.
          required: true
        - label: I have resolved all warnings from `brew doctor` and that did not fix my problem.
          required: true
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened (include all command output)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: Step-by-step reproduction instructions (by running `brew` commands)
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: "`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output"
    validations:
      required: false
