name: bump outdated

on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Comma-separated list of formulae'
        type: string
      force:
        description: 'Force PR creation (ignore existing)'
        required: true
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * 1

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope enabled
          token: ${{ secrets.TOKEN }}
          tap: davidchall/hep
          formula: ${{ inputs.formula }}
          force: ${{ inputs.force }}
          livecheck: true
